const express = require("express")
const router = express.Router()
const userRoute = require("./facebookLogin/user.route")
const paymentRoute = require("./razorpayIntegration/razorPay.route")
const WordToPdfRoute = require("./convertWordToPdf/WordToPdf.route")
const otpRoute = require("./sentOtp/otp.route")
const promiseHandlingRoute = require("./PromiseHandling/promiseHandling.route")
router.use("/user", userRoute)
router.use("/payment", paymentRoute)
router.use("/WordToPdf", WordToPdfRoute)
router.use("/otp", otpRoute)
router.use("/promiseHandling", promiseHandlingRoute)
module.exports = router